server:
  port: 8099

spring:
  dubbo:
    application:
      name: consumer
    registry:                 #注册中心配置，用于配置连接注册中心相关信息。
      address: zookeeper://192.168.60.250:2181
      protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
        name: dubbo
        port: 20881
      scan: com.example.consumer.controller
